name: Deploy mainproject to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (optional)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./mainproject

      - name: Publish
        uses: actions/deploy-pages@v1
